//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShadow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int Calls_CallID { get; set; }
        public System.TimeSpan Calls_StartTime { get; set; }
        public System.TimeSpan Calls_EndTime { get; set; }
        public string Calls_DaysOfWeek { get; set; }
    }
}
