//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShadow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int Events_EventID { get; set; }
        public string Events_Name { get; set; }
        public System.DateTime Events_Date { get; set; }
        public System.TimeSpan Events_Time { get; set; }
        public int Events_RoomID { get; set; }
        public int Events_GroupID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
