//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShadow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Schedule_ScheduleID { get; set; }
        public int Schedule_WeekID { get; set; }
        public int Schedule_GroupID { get; set; }
        public int Schedule_TeacherID { get; set; }
        public int Schedule_RoomID { get; set; }
        public int? Schedule_ClassTypeID { get; set; }
        public int Schedule_SubjectID { get; set; }
        public System.TimeSpan Schedule_StartTime { get; set; }
        public System.TimeSpan Schedule_EndTime { get; set; }
    
        public virtual ClassTypes ClassTypes { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual Weeks Weeks { get; set; }
    }
}
