//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShadow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int Settings_SettingID { get; set; }
        public string Settings_Name { get; set; }
        public string Settings_Value { get; set; }
    }
}
