//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShadow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScheduleSystemEntities : DbContext
    {

        private static ScheduleSystemEntities _context;

        public static ScheduleSystemEntities GetContext()
        {
            if (_context == null)
                _context = new ScheduleSystemEntities();

            return _context;
        }

        public ScheduleSystemEntities()
            : base("name=ScheduleSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calls> Calls { get; set; }
        public virtual DbSet<ClassTypes> ClassTypes { get; set; }
        public virtual DbSet<Constraints> Constraints { get; set; }
        public virtual DbSet<Curriculum> Curriculum { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Priorities> Priorities { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Subgroups> Subgroups { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Weeks> Weeks { get; set; }
    }
}
